#!/usr/bin/env python3
"""
Path-scoped autoModules for the NixOS kernel.

nixpkgs' `autoModules = true` answers "m" to EVERY kconfig question it has no
explicit answer for (pkgs/os-specific/linux/kernel/generate-config.pl):

    # Build everything as a module if possible.
    $answer = "m" if $autoModules && $alts =~ ... && !($preferBuiltin && $alts =~ /Y/);

That is why a headless ARMv5 NAS ends up compiling DRM drivers and IIO pressure
sensors. `autoModules = false` is the opposite extreme: you get only what the
defconfig and your explicit list ask for, and an unforeseen USB dongle means a
kernel rebuild.

This script is the middle ground. kconfig symbols are not path-qualified, but the
Kconfig FILES that define them are, so "every driver under drivers/usb" is a
well-defined set: walk those files and collect the symbols they declare.

Only `tristate` symbols are emitted - a `bool` symbol cannot be "m".

The output is a plain list of symbol names. configuration.nix turns each into
`lib.kernel.option lib.kernel.module`, i.e. the "NAME? m" form that
generate-config.pl treats as optional, so symbols whose dependencies are unmet
are skipped instead of failing the build.

Regenerate whenever the kernel minor version changes:

    python3 gen-driver-modules.py <unpacked-kernel-src> > driver-modules.nix

Adapting to another machine means editing INCLUDE/EXCLUDE below. The useful
question is "what might someone plug in?", not "what does this board have?" -
anything soldered on should be an explicit entry in structuredExtraConfig.
"""
import os, re, sys

# Paths whose drivers we want available as modules "just in case".
INCLUDE = [
    "drivers/usb",       # host controllers, storage, serial, audio, ...
    "drivers/net/usb",   # USB ethernet dongles: asix, r8152, cdc_ether, ...
    "drivers/hid",       # USB keyboards, and whatever else gets plugged in
    # NixOS's firewall is iptables-nft and needs the netfilter/nftables modules.
    # With autoModules on these came for free; with it off the whole subsystem
    # vanished and firewall.service died with
    #   iptables: Failed to initialize nft: Protocol not supported
    # nixpkgs' common-config enables NF_TABLES_INET, NF_TABLES_IPV4 and friends
    # but never NF_TABLES itself - autoModules used to supply that implicitly.
    "net/netfilter",
    "net/ipv4/netfilter",
    "net/ipv6/netfilter",
]
# Subtrees under INCLUDE that are not worth the build time.
EXCLUDE = [
    "drivers/usb/gadget",  # device/peripheral mode; this board is usb0Mode=host
    "drivers/usb/musb",    # not a Kirkwood controller
    "drivers/usb/dwc2",
    "drivers/usb/dwc3",
    "drivers/usb/chipidea",
    "drivers/usb/cdns3",
]

CONFIG_RE = re.compile(r"^\s*(?:menu)?config\s+([A-Za-z0-9_]+)\s*$")
TYPE_RE   = re.compile(r"^\s+(tristate|bool|int|hex|string)\b")
# A new block starts at any of these; used to bound the type search.
BOUNDARY_RE = re.compile(r"^\s*(?:(?:menu)?config\s|endmenu|endchoice|choice\b|source\s|menu\s|if\s|endif)")


def tristate_symbols(path):
    """Yield every tristate symbol declared in one Kconfig file."""
    out = []
    try:
        lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
    except OSError:
        return out
    i = 0
    while i < len(lines):
        m = CONFIG_RE.match(lines[i])
        if not m:
            i += 1
            continue
        sym = m.group(1)
        # Scan the block body for its type keyword.
        j = i + 1
        while j < len(lines):
            if BOUNDARY_RE.match(lines[j]):
                break
            t = TYPE_RE.match(lines[j])
            if t:
                if t.group(1) == "tristate":
                    out.append(sym)
                break
            j += 1
        i = j if j > i else i + 1
    return out


def collect(root, include, exclude):
    syms, per_path = set(), {}
    for inc in include:
        base = os.path.join(root, inc)
        found = set()
        for dirpath, _dirnames, filenames in os.walk(base):
            rel = os.path.relpath(dirpath, root)
            if any(rel == e or rel.startswith(e + os.sep) for e in exclude):
                continue
            for fn in filenames:
                if fn == "Kconfig" or fn.startswith("Kconfig."):
                    found.update(tristate_symbols(os.path.join(dirpath, fn)))
        per_path[inc] = found
        syms |= found
    return syms, per_path


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen-driver-modules.py <unpacked-kernel-source-root>")
    root = sys.argv[1]
    syms, per_path = collect(root, INCLUDE, EXCLUDE)
    for p, s in per_path.items():
        print(f"# {p}: {len(s)} tristate symbols", file=sys.stderr)
    print(f"# TOTAL (deduplicated): {len(syms)}", file=sys.stderr)

    print("# Generated by gen-driver-modules.py - do not edit by hand.")
    print(f"# kernel source: {os.path.basename(root)}")
    print(f"# include: {', '.join(INCLUDE)}")
    print(f"# exclude: {', '.join(EXCLUDE)}")
    print(f"# {len(syms)} tristate symbols")
    print("[")
    for s in sorted(syms):
        print(f'  "{s}"')
    print("]")


if __name__ == "__main__":
    main()
